### ISSUE TITLE
Unable to deploy?

### ISSUE THREAD

**Issue by Ryandesigns09** [wcassels/discord-topshot#1]
I know how to run go projects but I'm getting the errors below on run. I added token.txt to the document root but still no dice. Does it still work?

.\client.go:153:26: undefined: SaleMoment
.\client.go:171:18: undefined: GetAddress
.\client.go:184:18: undefined: GetAddress
.\client.go:299:72: undefined: SaleMoment
.\client.go:329:11: undefined: MomentPurchasedEvent
.\client.go:330:25: undefined: GetSaleMomentFromOwnerAtBlock
.\client.go:345:58: undefined: SaleMoment
.\client.go:360:46: undefined: SaleMoment

**Comment by wcassels** [comment]
Hey, you would need to `go run client.go web_nba.go flow_utils.go`

It does work, but the code is nowhere near finished and there are still a number of issues to be fixed that I don't really have the time for right now, most notably that after a period of high activity the bot falls behind and breaks.

I've just pushed a change that removes some hardcoded variables, so if you really want to get this working I'd suggest pulling, and adding your own discord user ID on line 155 of client.go. You can then configure alerts with !alert, but I haven't written any documentation so you'll have to read the alertHandler code to see the options there. And as I said, the bot eventually breaks anyway.

**Comment by Ryandesigns09** [comment]
Great thanks, got it up and running. Had the bot join the channel and can query it, however when I type !alert https://www.nbatopshot.com/listings/p2p/122b048d-585e-4c63-8275-c23949576fd6+1d8726cd-08f1-4725-a85f-ac56470bad3b 100 the go app closes and I need to restart. Should it be a different command / query for me to add new alerts?
